package errs

import (
	"emviwiki/shared/rest"
	"errors"
)

var (
	TxBegin       = errors.New("error starting transaction")
	TxCommit      = errors.New("error committing transaction")
	Saving        = errors.New("error on save")
	UploadingFile = errors.New("error uploading file to content server")

	FindingLatestArticleContent    = rest.NewApiError("Latest article content not found", "")
	NoTitle                        = rest.NewApiError("Title empty", "title")
	TitleLen                       = rest.NewApiError("Title too long", "title")
	CommitMsgLen                   = rest.NewApiError("Commit message too long", "message")
	LanguageNotFound               = rest.NewApiError("Language not found", "")
	UserOrUserGroupNotFound        = rest.NewApiError("User or user group not found", "")
	PermissionDenied               = rest.NewApiError("Permission denied", "")
	ArticlePermissionDenied        = rest.NewApiError("Article permission denied", "")
	NoNamesProvided                = rest.NewApiError("No names were provided", "")
	NameTooShort                   = rest.NewApiError("Name too short", "name")
	NameTooLong                    = rest.NewApiError("Name too long", "name")
	InfoTooLong                    = rest.NewApiError("Info too long", "info")
	ArticleListNotFound            = rest.NewApiError("Article list not found", "")
	ArticleNotFound                = rest.NewApiError("Article not found", "")
	InvalidPos                     = rest.NewApiError("Position invalid", "")
	PosNotFound                    = rest.NewApiError("Position not found", "")
	UserNotFound                   = rest.NewApiError("User not found", "")
	MemberNotFound                 = rest.NewApiError("Member not found", "")
	ModeratorYourself              = rest.NewApiError("Cannot remove moderator from yourself", "")
	RemoveYourself                 = rest.NewApiError("Cannot remove yourself", "")
	NonPublicFeedWithoutAccess     = rest.NewApiError("Someone must have access to non public feed", "")
	ReasonNotFound                 = rest.NewApiError("Reason not found", "")
	RefObjectUnknown               = rest.NewApiError("The referenced object is of unknown type", "")
	FeedAccessNotFound             = rest.NewApiError("Feed access not found", "")
	ChangeAdminYourself            = rest.NewApiError("You cannot change admin privileges on yourself", "")
	EmailInvalid                   = rest.NewApiError("Email invalid", "email")
	InvitationNotFound             = rest.NewApiError("Invitation not found", "")
	IsMemberAlready                = rest.NewApiError("User is a member already", "")
	UsernameTooShort               = rest.NewApiError("Username too short", "username")
	UsernameTooLong                = rest.NewApiError("Username too long", "username")
	UsernameInvalid                = rest.NewApiError("Username invalid", "username")
	UsernameInUse                  = rest.NewApiError("Username in use already", "username")
	PhoneLen                       = rest.NewApiError("Phone too long", "phone")
	MobileLen                      = rest.NewApiError("Mobile too long", "mobile")
	NotificationIntervalInvalid    = rest.NewApiError("Notification interval invalid", "")
	NoObjectToObserve              = rest.NewApiError("No object to observe was set", "")
	DomainInUse                    = rest.NewApiError("Domain in use already", "domain")
	DomainNumberFirstChar          = rest.NewApiError("Domain must start with letter", "domain")
	DomainLastChar                 = rest.NewApiError("Domain must end with letter or number", "domain")
	DomainInvalidChar              = rest.NewApiError("Domain contains invalid character", "domain")
	UsernameFirstChar              = rest.NewApiError("Username must start with letter or number", "username")
	UsernameLastChar               = rest.NewApiError("Username must end with letter or number", "username")
	UsernameInvalidChar            = rest.NewApiError("Username contains invalid character", "username")
	OrganizationNotFound           = rest.NewApiError("Organization not found", "")
	NameDoesNotMatch               = rest.NewApiError("Name does not match the organizations name", "name")
	TagEmpty                       = rest.NewApiError("Tag empty", "tag")
	TagInvalid                     = rest.NewApiError("Tag invalid", "tag")
	TagLen                         = rest.NewApiError("Tag too long", "tag")
	TagNameExistsAlready           = rest.NewApiError("Tag exists already", "tag")
	MaxTagsReached                 = rest.NewApiError("Maximum number of tags reached", "tag")
	TagNotFound                    = rest.NewApiError("Tag not found", "")
	GroupNotFound                  = rest.NewApiError("Group not found", "")
	NameInUse                      = rest.NewApiError("Name in use already", "name")
	GroupToAddNotFound             = rest.NewApiError("Group to add not found", "")
	DomainNotAllowed               = rest.NewApiError("Domain not allowed", "domain")
	FileNotFound                   = rest.NewApiError("File not found", "")
	IO                             = rest.NewApiError("IO error", "")
	MessageTooShort                = rest.NewApiError("Message too short", "message")
	MessageTooLong                 = rest.NewApiError("Message too long", "message")
	UserDataInvalid                = rest.NewApiError("User data invalid", "")
	DomainTooShort                 = rest.NewApiError("Domain too short", "domain")
	DomainTooLong                  = rest.NewApiError("Domain too long", "domain")
	LanguageExists                 = rest.NewApiError("Language exists already", "code")
	LanguageInvalid                = rest.NewApiError("Language invalid", "code")
	ArticleContentVersionNotFound  = rest.NewApiError("Article content version not found", "")
	ArticleContentVersionInvalid   = rest.NewApiError("Article content version invalid", "")
	ArticleContentRemainingVersion = rest.NewApiError("Article content remaining version cannot be deleted", "")
	RequiresExpertVersion          = rest.NewApiError("Requires expert version", "")
	ChangeReadOnlyYourself         = rest.NewApiError("You cannot change write privileges on yourself", "")
	MaxStorageReached              = rest.NewApiError("Maximum storage capacity reached", "")
	NoObjectToBookmark             = rest.NewApiError("No object to bookmark was set", "")
	NoObjectToPin                  = rest.NewApiError("No object to pin was set", "")
	OrganizationOwner              = rest.NewApiError("Organization owner cannot be changed", "")
	OrganizationOwnerLeave         = rest.NewApiError("Organization owner cannot leave", "name")
	MaxFreeOrganizationsReached    = rest.NewApiError("Maximum free organizations reached", "")
	DefaultLanguageInvalid         = rest.NewApiError("Language invalid", "default_lang")
	TagExistsAlready               = rest.NewApiError("Tag exists already", "")
	FileType                       = rest.NewApiError("File type not allowed", "")
	MaxListsReached                = rest.NewApiError("Maximum number of lists reached", "")
	MaxArticlesReached             = rest.NewApiError("Maximum number of articles reached", "")
	RemoveModeratorAccess          = rest.NewApiError("No moderator access remaining after operation", "")
	ClientNotFound                 = rest.NewApiError("Client not found", "")
	ClientExistsAlready            = rest.NewApiError("Client exists already", "name")
	NameEmpty                      = rest.NewApiError("Name empty", "name")
	NameLen                        = rest.NewApiError("Name too long", "name")
	ScopeInvalid                   = rest.NewApiError("Scope invalid", "")
	ColorModeInvalid               = rest.NewApiError("Color mode invalid", "")
	NewsletterNotFound             = rest.NewApiError("Newsletter not found", "")
	SubjectTooLong                 = rest.NewApiError("Subject too long", "subject")
	SubjectTooShort                = rest.NewApiError("Subject too short", "subject")
	RecommendationsNotFound        = rest.NewApiError("Recommendations not found", "")
	UnknownArticleFormat           = rest.NewApiError("Unknown article format", "format")
	UnpublishedArticle             = rest.NewApiError("Unpublished article", "")

	// billing errors
	BillingIntervalInvalid   = rest.NewApiError("Billing interval invalid", "")
	ProcessingPayment        = rest.NewApiError("Error processing payment", "")
	CustomerNotFound         = rest.NewApiError("Customer not found", "")
	SubscriptionNotFound     = rest.NewApiError("Subscription not found", "")
	ActiveSubscriptionFound  = rest.NewApiError("Active subscription found", "")
	SubscriptionCancelled    = rest.NewApiError("Subscription cancelled", "")
	SubscriptionNotCancelled = rest.NewApiError("Subscription not cancelled", "")
	CancellingSubscription   = rest.NewApiError("Error cancelling subscription", "")
	ResumingSubscription     = rest.NewApiError("Error resuming subscription", "")
	UpdatingSubscription     = rest.NewApiError("Error updating subscription", "")
	UpdatingCustomer         = rest.NewApiError("Error updating customer", "")
	DeletingCustomer         = rest.NewApiError("Error deleting customer", "")
	ReadingInvoices          = rest.NewApiError("Error reading invoices", "")
	PaymentMethodNotFound    = rest.NewApiError("Payment method not found", "")
	PaymentIntentNotFound    = rest.NewApiError("Payment intent not found", "")
	CountryInvalid           = rest.NewApiError("Country invalid", "country")
	AddressLineTooShort      = rest.NewApiError("Address line too short", "address_line_1")
	PostalCodeTooShort       = rest.NewApiError("Postal code too short", "postal_code")
	CityTooShort             = rest.NewApiError("City too short", "city")
)
